version: 2
updates:
  # Enable version updates for Rust dependencies in bootloader
  - package-ecosystem: "cargo"
    directory: "/sentient-bootloader"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    reviewers:
      - "mscrnt"
    labels:
      - "dependencies"
      - "rust"
      - "bootloader"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Enable version updates for Rust dependencies in kernel
  - package-ecosystem: "cargo"
    directory: "/sentient-kernel"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    reviewers:
      - "mscrnt"
    labels:
      - "dependencies"
      - "rust"
      - "kernel"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Keep GitHub Actions up to date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    reviewers:
      - "mscrnt"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"